### ISSUE TITLE
TODO for release 1.0

### ISSUE THREAD

**Issue by maheshauti96** [pchandle07/ShastraDaan#2]
p1

- [ ] share a school or clg link
- [ ] social share icons
- [ ] already raised/donated and its  progress bar population
- [ ] implement new design in React
- [ ] add back or home button

p2

- [ ] loader while searching for school
- [ ] add contact number field

p3

- [ ]
